---
title: "Class 1"
format: html
editor: visual
toc: true
---

## Introduction to R

### Arithmetic

```{r}
4+5
3-6
3*4
4/5
3^2
exp(1)
log(1)

1+2*3

1/9*9

```

### Variable Assignment

```{r}
x <- 12
1 == 1
x = 12

x^2

x <- 3

x^2

x <- 1
x <- x +1
x
```

\

### Vectors

```{r}
x <- c(43, 6, 2, 8, 32)
x

mean(x)
min(x)
max(x)
length(x)

```

#### Vector Arithmetic & Vectorisation

```{r}
x <- c(1,6,3)
y <- c(5,2,-1)
x + y

x - y
x*y
x/y
x^y

x <- c(1,10,100,1000,10000)
log(x,base=10)

log(x)

y <- c(1,2,3,4,5)
exp(y)

x <- c(1,2,3,4,5,6)
y <- c(5,4,7)
x + y

x <- c(1,2,3,4,5)
x + 1
```

#### Numerical Subsettings

```{r}
x <- c(1,6,2,3.5,1,59,6)

length(x)
x[1] # remeber R starts subsetting from 0

x[length(x)-1] # R can't subset backwards

x[c(1,2,3,4)] 

y <- c(T,T,F,T,F,F,T)
x[y]

x[x > 0] # useful for data analysis
x
x[-1]

z <- c(a = 1, b= 2, c= 3, b = 2)


```

### Matrices

```{r}
a <- matrix(data=1:24,nrow=4,ncol=6)

b <- matrix(data=1:24,nrow=4,ncol=6, byrow=T)

x <- matrix(1:24,nrow=4) 
```

#### Arithmetic

```{r}
x <- matrix(1:6,nrow=2,byrow=F)
y <- matrix(1:6,nrow=2,byrow=T)

x
y
# x + y    "Crtl + Shift + C"
# x-y
x * y
x / y

x %*% y

# Not all nXm matrices can be multiplied by each other

t(x)

```

#### Subsetting

```{r}
x <- matrix(1:9,nrow=3)
x[1,1]
x[2,3]

x[1:2,1:3]

x[x %% 2 == 0]

x[x<5] 

x[9]

```

```{r}

```

\

\

### Full Codes

```{r}
4+5
3-6
3*4
4/5
3^2
exp(1)
log(1)

1 + 2*3

1/9*9

x <- 12

x^2

x <- 3
x

x <- 1
x <- x + 1

x = 12

x <- c(43,6,1,2,8,32)
x

mean(x)
min(x)
max(x)
length(x)

x <- c(1,6,3)
y <- c(5,2,-1)
x + y

x - y
x*y
x/y
x^y

x <- c(1,10,100,1000,10000)
log(x,base=10)

y <- c(1,2,3,4,5)
exp(y)

x <- c(1,2,3,4,5,6)
y <- c(5,4,7)
x + y

x <- c(1,2,3,4,5)
x + 1

x <- c(1,6,2,3.5,1,59,6)
x[1]
x[3]
x[6]
y <- c(T,T,F,T,F,F,T)
x[y]
x[x > 3]
x[-1]
z <- c(a = 1, b= 2, c= 3, b = 2)
z

x <- matrix(data=1:24,nrow=4,ncol=6)
x
y <- matrix(data=1:24,nrow=4,ncol=6,byrow=T)
y

x <- matrix(1:6,nrow=2,byrow=F)
y <- matrix(1:6,nrow=2,byrow=T)
x + y
x - y
x * y
x / y

x <- matrix(1:9,nrow=3)
x[1,1]
x[2,3]

x[1:2,1:3]

x[x %% 2 == 0]

x[x<999]

x <- matrix(1:9,nrow=3)
x[1]

x[2]

```
