<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 2 Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Class 2 (Solution)_files/libs/clipboard/clipboard.min.js"></script>
<script src="Class 2 (Solution)_files/libs/quarto-html/quarto.js"></script>
<script src="Class 2 (Solution)_files/libs/quarto-html/popper.min.js"></script>
<script src="Class 2 (Solution)_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Class 2 (Solution)_files/libs/quarto-html/anchor.min.js"></script>
<link href="Class 2 (Solution)_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Class 2 (Solution)_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Class 2 (Solution)_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Class 2 (Solution)_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Class 2 (Solution)_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#class-2-27092023" id="toc-class-2-27092023" class="nav-link active" data-scroll-target="#class-2-27092023">Class 2 (27/09/2023)</a></li>
  <li><a href="#introduction-to-dplyr" id="toc-introduction-to-dplyr" class="nav-link" data-scroll-target="#introduction-to-dplyr">Introduction to dplyr</a>
  <ul class="collapse">
  <li><a href="#pipe-operator" id="toc-pipe-operator" class="nav-link" data-scroll-target="#pipe-operator">Pipe Operator</a></li>
  <li><a href="#tidyverse-collection-of-packages" id="toc-tidyverse-collection-of-packages" class="nav-link" data-scroll-target="#tidyverse-collection-of-packages">Tidyverse collection of packages</a></li>
  <li><a href="#dplyr---mutate" id="toc-dplyr---mutate" class="nav-link" data-scroll-target="#dplyr---mutate">Dplyr - mutate</a></li>
  <li><a href="#dplyr---select" id="toc-dplyr---select" class="nav-link" data-scroll-target="#dplyr---select">Dplyr - select</a></li>
  <li><a href="#dplyr---filter" id="toc-dplyr---filter" class="nav-link" data-scroll-target="#dplyr---filter">Dplyr - filter</a></li>
  <li><a href="#dplyrgroup_by-and-dplyrsummarise" id="toc-dplyrgroup_by-and-dplyrsummarise" class="nav-link" data-scroll-target="#dplyrgroup_by-and-dplyrsummarise">Dplyr::group_by and dplyr::summarise</a></li>
  <li><a href="#dplyrarrange" id="toc-dplyrarrange" class="nav-link" data-scroll-target="#dplyrarrange">Dplyr::arrange</a></li>
  <li><a href="#lexical-scoping-nse-optional" id="toc-lexical-scoping-nse-optional" class="nav-link" data-scroll-target="#lexical-scoping-nse-optional">Lexical Scoping &amp; NSE (Optional)</a></li>
  </ul></li>
  <li><a href="#case-study-a-motor-third-party-liability-policies" id="toc-case-study-a-motor-third-party-liability-policies" class="nav-link" data-scroll-target="#case-study-a-motor-third-party-liability-policies">Case Study: A Motor Third-party Liability Policies</a></li>
  <li><a href="#tasks" id="toc-tasks" class="nav-link" data-scroll-target="#tasks">Tasks</a></li>
  <li><a href="#additional-exercises-functions-in-r" id="toc-additional-exercises-functions-in-r" class="nav-link" data-scroll-target="#additional-exercises-functions-in-r">Additional Exercises Functions in R</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Class 2 Notebook</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="class-2-27092023" class="level2">
<h2 class="anchored" data-anchor-id="class-2-27092023">Class 2 (27/09/2023)</h2>
<p>In this class, we will go through the <code>dplyr</code> package in R.</p>
</section>
<section id="introduction-to-dplyr" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-dplyr">Introduction to dplyr</h2>
<section id="pipe-operator" class="level3">
<h3 class="anchored" data-anchor-id="pipe-operator">Pipe Operator</h3>
<p>In computation, we often have to chain multiple operations together. Consider a toy example. We want to calculate:</p>
<p><span class="math display">\[
\arctan(\sin(\exp(\Gamma(x))).
\]</span></p>
<p>Try and write it as is in the following code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">atan</span>(<span class="fu">sin</span>(<span class="fu">exp</span>(<span class="fu">gamma</span>(<span class="dv">1</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3897659</code></pre>
</div>
</div>
<p>However, as you may notice, this is difficult to read and error-prone (imagine counting parentheses whenever you write codes!).</p>
<p>In mathematics, we chain operations by composition:</p>
<p><span class="math display">\[
\arctan \circ \sin \circ \exp \circ \Gamma(x)
\]</span></p>
<p>In R specifically, we have the pipe operator <code>%&gt;%</code>, provided by the <code>magrittr</code> package. It allows you write the above as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span> gamma <span class="sc">%&gt;%</span> exp <span class="sc">%&gt;%</span> sin <span class="sc">%&gt;%</span> atan</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3897659</code></pre>
</div>
</div>
<p>The pipe <code>%&gt;%</code> takes the expression on its LHS, and pass it as the FIRST argument to the function on the RHS.</p>
<p>It’s helpful to read <code>%&gt;%</code> as “and then”. We applied the gamma function, and then the exponential function, and then the sine function, so on and so forth . . .</p>
<p>You can also supply additional arguments for piped functions (that the pipe feed into). As an example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="cn">NA</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span> <span class="fu">max</span>(<span class="at">na.rm=</span>T) <span class="co">#is the same as</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(x,<span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>Amongst the readers familiar with Object Oriented Programming, compare this with method chaining techniques.<br>
</p>
<p>As of the time of writing, R is considering implementing a native pipe operator.</p>
</section>
<section id="tidyverse-collection-of-packages" class="level3">
<h3 class="anchored" data-anchor-id="tidyverse-collection-of-packages">Tidyverse collection of packages</h3>
<ul>
<li><p>From the <code>tidyverse</code> website: The tidyverse is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures.</p></li>
<li><p><code>tidyverse</code> packages help to steamline the data cleansing and exploring process and also smooth out some quirks of R.</p></li>
<li><p>It is not a single package but a collection of packages. We will introduce them judiciously as we need them.</p></li>
<li><p><code>dplyr</code> (pronounced d-plier) is a package designed for cleansing and manipulating a data set. It is an amalgamation of “data frames” and the package <code>plyr</code>. Pliers, of course, are handy tools to have.</p></li>
<li><p>We will look at the 5 main functions: <code>mutate, select, filter, group_by</code> and <code>arrange</code>. For full potential of the package, you are encouraged to look at its documentation.</p></li>
<li><p>Although not compulsory, you are encouraged to try recreating all examples in these notes in base R.</p></li>
</ul>
</section>
<section id="dplyr---mutate" class="level3">
<h3 class="anchored" data-anchor-id="dplyr---mutate">Dplyr - mutate</h3>
<ul>
<li><p>The general syntax is: <code>mutate(dataset, output_column = f(input_columns))</code></p></li>
<li><p><code>output_column</code> will be added in as a new column in the dataset. If there is already a column named <code>output_column</code>, it will be overwritten.</p></li>
<li><p><code>f</code> is a function returning a vector of the same length. The length preservation is important - since the output will be pushed into the data frame</p></li>
<li><p>As demonstration, we will consider the two built-in data sets in R: <code>mtcars</code> and <code>iris</code>. For demo purposes, there are no benefits gained from working on a large data sets. Worry not, you will be given a “proper” data set to work with.</p></li>
</ul>
<p>Let’s take a look at the <code>mtcars</code> as an example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<ul>
<li>The row names are not actually part of the data frame. It is stored as an additional attributes. The technical implication is that this information might be lost if fed to a function that doesn’t preserve attributes. For instance:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the 'dplyr' package. The 'warn.conflicts = FALSE' option ensures that </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># no warning messages are printed when there are naming conflicts with other packages.</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 'as_tibble' converts the given dataset (in this case, 'mtcars') into a tibble, </span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># which is a modern version of data frames in R provided by the 'tibble' package. </span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Tibbles are more user-friendly and have some advantages over traditional data frames.</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>(mtcars) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first 6 rows of the resulting tibble.</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
    mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  21       6   160   110  3.9   2.62  16.5     0     1     4     4
2  21       6   160   110  3.9   2.88  17.0     0     1     4     4
3  22.8     4   108    93  3.85  2.32  18.6     1     1     4     1
4  21.4     6   258   110  3.08  3.22  19.4     1     0     3     1
5  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2
6  18.1     6   225   105  2.76  3.46  20.2     1     0     3     1</code></pre>
</div>
</div>
<p><strong>Q: What does <code>warn.conflicts - FALSE</code> and <code>as_tibble</code> mean? Comment your description in the code above.</strong></p>
<ul>
<li>We want to create a new column in the data frame that stores the column name. This is done simply by:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(mtcars, <span class="at">modelNames =</span> <span class="fu">rownames</span>(mtcars)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="at">n=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              mpg cyl disp  hp drat    wt  qsec vs am gear carb    modelNames
Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4     Mazda RX4
Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4 Mazda RX4 Wag</code></pre>
</div>
</div>
<p>Within a function call, <code>&lt;-</code> and <code>=</code> are not equivalent. Strange behavior might result. Please copy the code above and see what happens :)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mutate(mtcars, modelNames &lt;- rownames(mtcars)) %&gt;% head(n=2)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Here, you've used the assignment operator (&lt;-) instead of the equals sign. What this does is it assigns the row names of the mtcars dataset to a new variable modelNames in the global environment, not within the mutate function. As a result, the mutate function doesn't actually add a new column, and you'll just get the original mtcars dataset without any modifications.</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Using &lt;- within function calls like this can lead to confusing outcomes and is generally considered bad practice. Always use = when specifying arguments or making assignments within function calls.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>mutate and other dplyr functions are designed to work seamlessly with the pipe operator - so let’s do just that.</p></li>
<li><p>For another example, suppose that you suspect that <code>mpg</code> is a linear function of the square root of <code>disp</code>. Let us create a column for that:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">root_disp =</span> <span class="fu">sqrt</span>(disp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
                    root_disp
Mazda RX4           12.649111
Mazda RX4 Wag       12.649111
Datsun 710          10.392305
Hornet 4 Drive      16.062378
Hornet Sportabout   18.973666
Valiant             15.000000
Duster 360          18.973666
Merc 240D           12.111978
Merc 230            11.865918
Merc 280            12.946042
Merc 280C           12.946042
Merc 450SE          16.607227
Merc 450SL          16.607227
Merc 450SLC         16.607227
Cadillac Fleetwood  21.725561
Lincoln Continental 21.447611
Chrysler Imperial   20.976177
Fiat 128             8.871302
Honda Civic          8.700575
Toyota Corolla       8.432082
Toyota Corona       10.959015
Dodge Challenger    17.832555
AMC Javelin         17.435596
Camaro Z28          18.708287
Pontiac Firebird    20.000000
Fiat X1-9            8.888194
Porsche 914-2       10.968136
Lotus Europa         9.751923
Ford Pantera L      18.734994
Ferrari Dino        12.041595
Maserati Bora       17.349352
Volvo 142E          11.000000</code></pre>
</div>
</div>
<ul>
<li>The input part can contain multiple columns, as in the following example. The calculations are nonsensical, but they demonstrate the technique at a mechanical level:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">outputCol =</span> mpg <span class="sc">+</span> cyl<span class="sc">*</span>disp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
                    outputCol
Mazda RX4               981.0
Mazda RX4 Wag           981.0
Datsun 710              454.8
Hornet 4 Drive         1569.4
Hornet Sportabout      2898.7
Valiant                1368.1
Duster 360             2894.3
Merc 240D               611.2
Merc 230                586.0
Merc 280               1024.8
Merc 280C              1023.4
Merc 450SE             2222.8
Merc 450SL             2223.7
Merc 450SLC            2221.6
Cadillac Fleetwood     3786.4
Lincoln Continental    3690.4
Chrysler Imperial      3534.7
Fiat 128                347.2
Honda Civic             333.2
Toyota Corolla          318.3
Toyota Corona           501.9
Dodge Challenger       2559.5
AMC Javelin            2447.2
Camaro Z28             2813.3
Pontiac Firebird       3219.2
Fiat X1-9               343.3
Porsche 914-2           507.2
Lotus Europa            410.8
Ford Pantera L         2823.8
Ferrari Dino            889.7
Maserati Bora          2423.0
Volvo 142E              505.4</code></pre>
</div>
</div>
</section>
<section id="dplyr---select" class="level3">
<h3 class="anchored" data-anchor-id="dplyr---select">Dplyr - select</h3>
<ul>
<li><p>In insurance, you often have enormous data sets with tens or even hundreds of columns, many of which might be irrelevant.</p></li>
<li><p>You can use the select function to retain only the desired columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">select</span>(cyl, disp, hp) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="at">n =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              cyl disp  hp
Mazda RX4       6  160 110
Mazda RX4 Wag   6  160 110</code></pre>
</div>
</div></li>
<li><p>You can chain mutate and select by the pipe operator. It works because these functions take a data frame as input and return a data frame as output, which can then be fed into another data-frame-consuming function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">outputCol =</span> mpg <span class="sc">+</span> cyl<span class="sc">*</span>disp) <span class="sc">%&gt;%</span> <span class="fu">select</span>(mpg,cyl,disp,outputCol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp outputCol
Mazda RX4           21.0   6 160.0     981.0
Mazda RX4 Wag       21.0   6 160.0     981.0
Datsun 710          22.8   4 108.0     454.8
Hornet 4 Drive      21.4   6 258.0    1569.4
Hornet Sportabout   18.7   8 360.0    2898.7
Valiant             18.1   6 225.0    1368.1
Duster 360          14.3   8 360.0    2894.3
Merc 240D           24.4   4 146.7     611.2
Merc 230            22.8   4 140.8     586.0
Merc 280            19.2   6 167.6    1024.8
Merc 280C           17.8   6 167.6    1023.4
Merc 450SE          16.4   8 275.8    2222.8
Merc 450SL          17.3   8 275.8    2223.7
Merc 450SLC         15.2   8 275.8    2221.6
Cadillac Fleetwood  10.4   8 472.0    3786.4
Lincoln Continental 10.4   8 460.0    3690.4
Chrysler Imperial   14.7   8 440.0    3534.7
Fiat 128            32.4   4  78.7     347.2
Honda Civic         30.4   4  75.7     333.2
Toyota Corolla      33.9   4  71.1     318.3
Toyota Corona       21.5   4 120.1     501.9
Dodge Challenger    15.5   8 318.0    2559.5
AMC Javelin         15.2   8 304.0    2447.2
Camaro Z28          13.3   8 350.0    2813.3
Pontiac Firebird    19.2   8 400.0    3219.2
Fiat X1-9           27.3   4  79.0     343.3
Porsche 914-2       26.0   4 120.3     507.2
Lotus Europa        30.4   4  95.1     410.8
Ford Pantera L      15.8   8 351.0    2823.8
Ferrari Dino        19.7   6 145.0     889.7
Maserati Bora       15.0   8 301.0    2423.0
Volvo 142E          21.4   4 121.0     505.4</code></pre>
</div>
</div></li>
<li><p>In certain cases, you want to exclude columns from a data frame instead. Here’s an example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!</span>cyl) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               mpg disp  hp drat    wt  qsec vs am gear carb
Mazda RX4     21.0  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag 21.0  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710    22.8  108  93 3.85 2.320 18.61  1  1    4    1</code></pre>
</div>
</div></li>
<li><p>If you want to exclude multiple columns, this doesn’t work <code>mtcars %&gt;% select(!cyl, !am)</code></p></li>
<li><p>Either of these work though:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!</span>cyl <span class="sc">&amp;</span> <span class="sc">!</span>am)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg  disp  hp drat    wt  qsec vs gear carb
Mazda RX4           21.0 160.0 110 3.90 2.620 16.46  0    4    4
Mazda RX4 Wag       21.0 160.0 110 3.90 2.875 17.02  0    4    4
Datsun 710          22.8 108.0  93 3.85 2.320 18.61  1    4    1
Hornet 4 Drive      21.4 258.0 110 3.08 3.215 19.44  1    3    1
Hornet Sportabout   18.7 360.0 175 3.15 3.440 17.02  0    3    2
Valiant             18.1 225.0 105 2.76 3.460 20.22  1    3    1
Duster 360          14.3 360.0 245 3.21 3.570 15.84  0    3    4
Merc 240D           24.4 146.7  62 3.69 3.190 20.00  1    4    2
Merc 230            22.8 140.8  95 3.92 3.150 22.90  1    4    2
Merc 280            19.2 167.6 123 3.92 3.440 18.30  1    4    4
Merc 280C           17.8 167.6 123 3.92 3.440 18.90  1    4    4
Merc 450SE          16.4 275.8 180 3.07 4.070 17.40  0    3    3
Merc 450SL          17.3 275.8 180 3.07 3.730 17.60  0    3    3
Merc 450SLC         15.2 275.8 180 3.07 3.780 18.00  0    3    3
Cadillac Fleetwood  10.4 472.0 205 2.93 5.250 17.98  0    3    4
Lincoln Continental 10.4 460.0 215 3.00 5.424 17.82  0    3    4
Chrysler Imperial   14.7 440.0 230 3.23 5.345 17.42  0    3    4
Fiat 128            32.4  78.7  66 4.08 2.200 19.47  1    4    1
Honda Civic         30.4  75.7  52 4.93 1.615 18.52  1    4    2
Toyota Corolla      33.9  71.1  65 4.22 1.835 19.90  1    4    1
Toyota Corona       21.5 120.1  97 3.70 2.465 20.01  1    3    1
Dodge Challenger    15.5 318.0 150 2.76 3.520 16.87  0    3    2
AMC Javelin         15.2 304.0 150 3.15 3.435 17.30  0    3    2
Camaro Z28          13.3 350.0 245 3.73 3.840 15.41  0    3    4
Pontiac Firebird    19.2 400.0 175 3.08 3.845 17.05  0    3    2
Fiat X1-9           27.3  79.0  66 4.08 1.935 18.90  1    4    1
Porsche 914-2       26.0 120.3  91 4.43 2.140 16.70  0    5    2
Lotus Europa        30.4  95.1 113 3.77 1.513 16.90  1    5    2
Ford Pantera L      15.8 351.0 264 4.22 3.170 14.50  0    5    4
Ferrari Dino        19.7 145.0 175 3.62 2.770 15.50  0    5    6
Maserati Bora       15.0 301.0 335 3.54 3.570 14.60  0    5    8
Volvo 142E          21.4 121.0 109 4.11 2.780 18.60  1    4    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!</span>cyl) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">!</span>am)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg  disp  hp drat    wt  qsec vs gear carb
Mazda RX4           21.0 160.0 110 3.90 2.620 16.46  0    4    4
Mazda RX4 Wag       21.0 160.0 110 3.90 2.875 17.02  0    4    4
Datsun 710          22.8 108.0  93 3.85 2.320 18.61  1    4    1
Hornet 4 Drive      21.4 258.0 110 3.08 3.215 19.44  1    3    1
Hornet Sportabout   18.7 360.0 175 3.15 3.440 17.02  0    3    2
Valiant             18.1 225.0 105 2.76 3.460 20.22  1    3    1
Duster 360          14.3 360.0 245 3.21 3.570 15.84  0    3    4
Merc 240D           24.4 146.7  62 3.69 3.190 20.00  1    4    2
Merc 230            22.8 140.8  95 3.92 3.150 22.90  1    4    2
Merc 280            19.2 167.6 123 3.92 3.440 18.30  1    4    4
Merc 280C           17.8 167.6 123 3.92 3.440 18.90  1    4    4
Merc 450SE          16.4 275.8 180 3.07 4.070 17.40  0    3    3
Merc 450SL          17.3 275.8 180 3.07 3.730 17.60  0    3    3
Merc 450SLC         15.2 275.8 180 3.07 3.780 18.00  0    3    3
Cadillac Fleetwood  10.4 472.0 205 2.93 5.250 17.98  0    3    4
Lincoln Continental 10.4 460.0 215 3.00 5.424 17.82  0    3    4
Chrysler Imperial   14.7 440.0 230 3.23 5.345 17.42  0    3    4
Fiat 128            32.4  78.7  66 4.08 2.200 19.47  1    4    1
Honda Civic         30.4  75.7  52 4.93 1.615 18.52  1    4    2
Toyota Corolla      33.9  71.1  65 4.22 1.835 19.90  1    4    1
Toyota Corona       21.5 120.1  97 3.70 2.465 20.01  1    3    1
Dodge Challenger    15.5 318.0 150 2.76 3.520 16.87  0    3    2
AMC Javelin         15.2 304.0 150 3.15 3.435 17.30  0    3    2
Camaro Z28          13.3 350.0 245 3.73 3.840 15.41  0    3    4
Pontiac Firebird    19.2 400.0 175 3.08 3.845 17.05  0    3    2
Fiat X1-9           27.3  79.0  66 4.08 1.935 18.90  1    4    1
Porsche 914-2       26.0 120.3  91 4.43 2.140 16.70  0    5    2
Lotus Europa        30.4  95.1 113 3.77 1.513 16.90  1    5    2
Ford Pantera L      15.8 351.0 264 4.22 3.170 14.50  0    5    4
Ferrari Dino        19.7 145.0 175 3.62 2.770 15.50  0    5    6
Maserati Bora       15.0 301.0 335 3.54 3.570 14.60  0    5    8
Volvo 142E          21.4 121.0 109 4.11 2.780 18.60  1    4    2</code></pre>
</div>
</div></li>
<li><p>It is difficult to explain why mtcars%&gt;%select(!cyl,!am) doesn’t work without digging into the mechanics of tidyselect. We shall not do so.</p></li>
<li><p>These methods require one to explicitly name the columns. It is possible to select/deselect columns based on pattern matching or regular expression. See this for helper functions.</p></li>
</ul>
</section>
<section id="dplyr---filter" class="level3">
<h3 class="anchored" data-anchor-id="dplyr---filter">Dplyr - filter</h3>
<ul>
<li><p>This allows you to select a subset of the original data set satisfying a certain condition.</p></li>
<li><p>As an example, let us select the rows of <code>mtcars</code> where <code>cyl</code> has the value 6.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cyl <span class="sc">==</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4</code></pre>
</div>
</div></li>
<li><p>You can also combine multiple conditions using Boolean algebra. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cyl <span class="sc">==</span> <span class="dv">6</span> <span class="sc">&amp;</span> mpg <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4</code></pre>
</div>
</div></li>
<li><p>Since the “and” operator is used so often, <code>filter</code> has its own built-in syntax, where you can supply an arbitrary number of conditions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cyl <span class="sc">==</span> <span class="dv">6</span>, mpg <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4</code></pre>
</div>
</div></li>
<li><p>The original code combines the conditions <code>cyl == 6</code> AND <code>mpg &gt; 15</code> and filters based on this one condition. The second version filters twice, based on two conditions. The desired effect is the same in the end.</p></li>
</ul>
</section>
<section id="dplyrgroup_by-and-dplyrsummarise" class="level3">
<h3 class="anchored" data-anchor-id="dplyrgroup_by-and-dplyrsummarise">Dplyr::group_by and dplyr::summarise</h3>
<p><strong>Q: What does :: mean in R?</strong></p>
<ul>
<li><p>An Extremely powerful techniques when data entires can be categorised into groups.</p></li>
<li><p>For our example, consider the <code>iris</code> dataset. Each row is an observation from a flower, which can be one of the three species: <code>vetosa</code>, <code>versicolor</code>, and <code>virginica</code>.</p></li>
<li><p>Suppose that we want to find the mean <code>Sepal.Length</code> of each group. This involves partitioning <code>iris</code> into three sub-datasets, and compute the mean <code>Sepal.Length</code> three times.</p></li>
<li><p>A solution with <code>dplyr</code> can look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">%&gt;%</span><span class="fu">group_by</span>(Species)<span class="sc">%&gt;%</span><span class="fu">summarise</span>(<span class="at">meanLength =</span> <span class="fu">mean</span>(Sepal.Length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Species    meanLength
  &lt;fct&gt;           &lt;dbl&gt;
1 setosa           5.01
2 versicolor       5.94
3 virginica        6.59</code></pre>
</div>
</div></li>
<li><p>You can compute an arbitrary number of by-group summary statistics in one call to <code>summarise</code>, for instance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">%&gt;%</span><span class="fu">group_by</span>(Species)<span class="sc">%&gt;%</span><span class="fu">summarise</span>(<span class="at">meanLength =</span> <span class="fu">mean</span>(Sepal.Length),<span class="at">maxLength =</span> <span class="fu">max</span>(Sepal.Length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Species    meanLength maxLength
  &lt;fct&gt;           &lt;dbl&gt;     &lt;dbl&gt;
1 setosa           5.01       5.8
2 versicolor       5.94       7  
3 virginica        6.59       7.9</code></pre>
</div>
</div></li>
<li><p>Note that <code>group_by</code> partiions by unique values of the grouping column. Although it makes sense to group by a categorical column, we can equally well group by numeric columns.</p></li>
<li><p>To demonstrate this, let’s consider the <code>mtcars</code> dataset again. The <code>cyl</code> column is a numeric column showing the number of cylinders in a vehicle, but we can treat it as a categorical variable for vehicle type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">avgDisp =</span> <span class="fu">mean</span>(disp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
    cyl avgDisp
  &lt;dbl&gt;   &lt;dbl&gt;
1     4    105.
2     6    183.
3     8    353.</code></pre>
</div>
</div></li>
<li><p>If you want to categorise your data at a finer level than offered by one categorical variable, we can <code>group_by</code> multiple columns. As an example, given the number of <code>cyl</code>, we want to further distinguish between automatic <code>(am == 0)</code> and manual <code>(am==1)</code> vehicles.</p></li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(cyl, am) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">avgDisp =</span> <span class="fu">mean</span>(disp))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Q: We get the following note <code>`summarise()` has grouped output by 'cyl'. You can override using the `.groups` argument</code>, please investigate what this means and comment in the code above.</strong></p>
</section>
<section id="dplyrarrange" class="level3">
<h3 class="anchored" data-anchor-id="dplyrarrange">Dplyr::arrange</h3>
<ul>
<li><p>As the name suggests, this arranges the rows in a certain order. As an example, let’s arrange mtcars in the increasing order of mpg:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(mpg) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl disp  hp drat    wt  qsec vs am gear carb
Cadillac Fleetwood  10.4   8  472 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8  460 215 3.00 5.424 17.82  0  0    3    4
Camaro Z28          13.3   8  350 245 3.73 3.840 15.41  0  0    3    4
Duster 360          14.3   8  360 245 3.21 3.570 15.84  0  0    3    4
Chrysler Imperial   14.7   8  440 230 3.23 5.345 17.42  0  0    3    4
Maserati Bora       15.0   8  301 335 3.54 3.570 14.60  0  1    5    8</code></pre>
</div>
</div></li>
<li><p>For descending order:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(mpg)) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2</code></pre>
</div>
</div></li>
<li><p>You can also arrange by multiple columns, first by the number of <code>cyl</code>, then <code>mpg:</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(cyl, mpg) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Volvo 142E    21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
Toyota Corona 21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Datsun 710    22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Merc 230      22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 240D     24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Porsche 914-2 26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2</code></pre>
</div>
</div></li>
</ul>
</section>
<section id="lexical-scoping-nse-optional" class="level3">
<h3 class="anchored" data-anchor-id="lexical-scoping-nse-optional">Lexical Scoping &amp; NSE (Optional)</h3>
<ul>
<li><p>This section is optional, but it will help you understand more thoroughly how R looks for its variables, i.e.&nbsp;its scoping rules.</p></li>
<li><p>Let’s have a look at the following example. I have selected only the first two columns to make the output more succinct.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>external <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">32</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">%&gt;%</span><span class="fu">select</span>(mpg,cyl)<span class="sc">%&gt;%</span><span class="fu">mutate</span>(<span class="at">out1 =</span> cyl<span class="sc">^</span><span class="dv">2</span>,<span class="at">out2=</span>external<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl out1 out2
Mazda RX4           21.0   6   36    1
Mazda RX4 Wag       21.0   6   36    4
Datsun 710          22.8   4   16    9
Hornet 4 Drive      21.4   6   36   16
Hornet Sportabout   18.7   8   64   25
Valiant             18.1   6   36   36
Duster 360          14.3   8   64   49
Merc 240D           24.4   4   16   64
Merc 230            22.8   4   16   81
Merc 280            19.2   6   36  100
Merc 280C           17.8   6   36  121
Merc 450SE          16.4   8   64  144
Merc 450SL          17.3   8   64  169
Merc 450SLC         15.2   8   64  196
Cadillac Fleetwood  10.4   8   64  225
Lincoln Continental 10.4   8   64  256
Chrysler Imperial   14.7   8   64  289
Fiat 128            32.4   4   16  324
Honda Civic         30.4   4   16  361
Toyota Corolla      33.9   4   16  400
Toyota Corona       21.5   4   16  441
Dodge Challenger    15.5   8   64  484
AMC Javelin         15.2   8   64  529
Camaro Z28          13.3   8   64  576
Pontiac Firebird    19.2   8   64  625
Fiat X1-9           27.3   4   16  676
Porsche 914-2       26.0   4   16  729
Lotus Europa        30.4   4   16  784
Ford Pantera L      15.8   8   64  841
Ferrari Dino        19.7   6   36  900
Maserati Bora       15.0   8   64  961
Volvo 142E          21.4   4   16 1024</code></pre>
</div>
</div></li>
<li><p>When mutate evaluates the computations supplied to it, it will: Treat the columns of the master data frame as if they were variables, then If such a column cannot be found (e.g.&nbsp;the external variable above), it will search outside of the data frame for a variable whose name matches.</p></li>
<li><p>This mechanism is called lexical scoping. We will not explore this further, but the interested students are suggested to consult [Advanced R by Wickham].</p></li>
<li><p>Unfortunately this opens up the following issue, if you have another <code>cyl</code> variable defined outside the data frame, e.g: <code>cyl &lt;- 1:32</code>.</p></li>
<li><p>How to you target it in mutate? The easiest solution is to enforce some naming scheme to avoid this situation.</p></li>
<li><p>Let’s take a look at a tangential, but related, example.There are several ways in which one can load a package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>library can interpret both a string of characters and the codes. If supply codes, library will first convert this into a character strings.</p></li>
<li><p>In general, R can access the codes you type and convert them into strings. This behavior is called Non-Standard Evaluation (NSE).</p></li>
<li><p>The situation is a bit more complicated, for example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>dplyr <span class="ot">&lt;-</span> <span class="st">"purrr"</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>This seems rather ambiguous. What do you think R will do?</p></li>
<li><p>NSE is employed extensively in R, and thoroughly in <code>dplyr</code> and <code>tidyverse</code>.</p></li>
<li><p>Again, we will not explore this further. But if you’re not getting the expected results, scoping issues and NSE often are the source of errors. It is worth bearing in mind these concepts</p></li>
</ul>
</section>
</section>
<section id="case-study-a-motor-third-party-liability-policies" class="level2">
<h2 class="anchored" data-anchor-id="case-study-a-motor-third-party-liability-policies">Case Study: A Motor Third-party Liability Policies</h2>
<p>As an example, we look at a data set containing risk features and claim numbers collected for nearly 700,000 MTPL policies observed over a year.</p>
<p>We conduct an initial numerical analysis to prepare for regression modelling. The response variable for the regression is the number of claims of each policy during the exposure period. Among all the policies, 94.98% have no claims. 9 variables are selected to explain the response, including:</p>
<ol type="1">
<li><p>IDpol: policy ID.</p></li>
<li><p>ClaimNb: Number of claims during the exposure period</p></li>
<li><p>Exposure : The exposure period.</p></li>
<li><p>Area: The area code.</p></li>
<li><p>VehPower: The power of the car (oredered categorical).</p></li>
<li><p>VehAge: The vehicle age, in years</p></li>
<li><p>DrivAge: The driver age, in years</p></li>
<li><p>BonusMalus: Bonus/malus, between 50 and 350: &lt;100 means bonus, &gt;100 means malus in France.</p></li>
<li><p>VehBrand: The car brand (unordered categories).</p></li>
<li><p>VehGas: The car gas, Diesel or regular.</p></li>
<li><p>Density: The density of inhabitants (number of inhabitants per km2) in the city the driver of the car lives in.</p></li>
<li><p>Region: the policy regions in France (based on a standard French classification)</p></li>
</ol>
<p>Visit this <a href="https://www.openml.org/search?type=data&amp;sort=runs&amp;id=41214">link</a> and download the <code>.csv</code> spreadsheet. Install and load the package readr. Type <code>?readr::read_csv</code> to read its documentation. Use the following code to interactively load the data set. (Note: set session to current directory, save the data set in the same folder to run the code below)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"freMTPL2freq.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 678013 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): Area, VehBrand, VehGas, Region
dbl (8): IDpol, ClaimNb, Exposure, VehPower, VehAge, DrivAge, BonusMalus, De...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Use the function <code>str</code> to have a quick overview of the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spec_tbl_df [678,013 × 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ IDpol     : num [1:678013] 1 3 5 10 11 13 15 17 18 21 ...
 $ ClaimNb   : num [1:678013] 1 1 1 1 1 1 1 1 1 1 ...
 $ Exposure  : num [1:678013] 0.1 0.77 0.75 0.09 0.84 0.52 0.45 0.27 0.71 0.15 ...
 $ Area      : chr [1:678013] "D" "D" "B" "B" ...
 $ VehPower  : num [1:678013] 5 5 6 7 7 6 6 7 7 7 ...
 $ VehAge    : num [1:678013] 0 0 2 0 0 2 2 0 0 0 ...
 $ DrivAge   : num [1:678013] 55 55 52 46 46 38 38 33 33 41 ...
 $ BonusMalus: num [1:678013] 50 50 50 50 50 50 50 68 68 50 ...
 $ VehBrand  : chr [1:678013] "B12" "B12" "B12" "B12" ...
 $ VehGas    : chr [1:678013] "Regular" "Regular" "Diesel" "Diesel" ...
 $ Density   : num [1:678013] 1217 1217 54 76 76 ...
 $ Region    : chr [1:678013] "R82" "R82" "R22" "R72" ...
 - attr(*, "spec")=
  .. cols(
  ..   IDpol = col_double(),
  ..   ClaimNb = col_double(),
  ..   Exposure = col_double(),
  ..   Area = col_character(),
  ..   VehPower = col_double(),
  ..   VehAge = col_double(),
  ..   DrivAge = col_double(),
  ..   BonusMalus = col_double(),
  ..   VehBrand = col_character(),
  ..   VehGas = col_character(),
  ..   Density = col_double(),
  ..   Region = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
</section>
<section id="tasks" class="level2">
<h2 class="anchored" data-anchor-id="tasks">Tasks</h2>
<ol type="1">
<li><p><code>VehGas</code> is a character column. For regressions - it should be a factor column. A factor vector is made of underlying numeric data (for mathematical categorisation) and factor labels (to retain qualitative data). Use <code>mutate</code> to convert the <code>VehGas</code> column to a factor column. <em>Hint: Consult <code>?factor</code></em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">VehGas =</span> <span class="fu">factor</span>(VehGas))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Some entries have an excessively high <code>ClaimNb</code>. One possible reason is that they might be bulk policies. Similar issues are seen with <code>Exposure</code>. One crude way to address this is to bound the <code>ClaimNb</code> and <code>Exposure</code> columns from above by 4 and 1, respectively. <em>Hint: consult the documentation of the <code>pmin</code> and <code>pmax</code> functions in base R.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ClaimNb =</span> <span class="fu">pmin</span>(ClaimNb, <span class="dv">4</span>), </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Exposure =</span> <span class="fu">pmin</span>(Exposure, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>By using <code>mutate</code>, create a new column storing the logarithm of the <code>Exposure</code> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">logExposure =</span> <span class="fu">log</span>(Exposure))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Create a new column that maps <code>Area</code> to numerical data. For instance, map “A” to 1, “B” to 2, etc. <em>Hint: write a function for this, then use <code>mutate.</code></em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to map Area to numerical data</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>map_area_to_number <span class="ot">&lt;-</span> <span class="cf">function</span>(area) {</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  areas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>, <span class="st">"G"</span>, <span class="st">"H"</span>, <span class="st">"I"</span>, <span class="st">"J"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">which</span>(areas <span class="sc">==</span> area))</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">AreaNumeric =</span> <span class="fu">sapply</span>(Area, map_area_to_number))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ol>
</section>
<section id="additional-exercises-functions-in-r" class="level2">
<h2 class="anchored" data-anchor-id="additional-exercises-functions-in-r">Additional Exercises Functions in R</h2>
<ol type="1">
<li><p>Write an R function, <code>choose.members(n,c,p)</code>, that returns the number of ways to choose members from an organization of <span class="math inline">\(p\)</span> people to serve on an executive committee consisting of <span class="math inline">\(n\)</span> “named positions” (e.g., president, vice-president, treasurer, and so on...), and <span class="math inline">\(c\)</span> at-large members of equal rank, as the sample output below suggests. <em>Hint: Use the built-in functions: <code>factorial()</code> and <code>choose()</code>. First please use help and the name of each function, for example, <code>help(factorial)</code>.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exercise 1</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>choose.members <span class="ot">=</span> <span class="cf">function</span>(n,c,p) {</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">factorial</span>(n)<span class="sc">*</span><span class="fu">choose</span>(p,n)<span class="sc">*</span><span class="fu">choose</span>(p<span class="sc">-</span>n,c))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Write an R function, <code>number.sequence(n)</code>, that returns a vector that has the form <span class="math inline">\(\{22\cdot3, 32 \cdot 5, 42 \cdot 7, 52 \cdot 9,...\}\)</span> and has exactly <span class="math inline">\(n\)</span> terms, as the sample output below suggests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exercise 2</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>number.sequence <span class="ot">=</span> <span class="cf">function</span>(n) {</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  squares <span class="ot">=</span> (<span class="dv">2</span><span class="sc">:</span>(n<span class="sc">+</span><span class="dv">1</span>))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  odds <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(squares <span class="sc">*</span> odds)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li><p>Write a function <code>is.even(n)</code> in R that returns <code>TRUE</code> when <span class="math inline">\(n\)</span> is even and <code>FALSE</code> otherwise. Then, using <code>is.even(n)</code>, write a function <code>evens.in(v)</code> that returns a vector comprised of the even integers in a vector <span class="math inline">\(v\)</span> of integers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exercise 3</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>is.even <span class="ot">=</span> <span class="cf">function</span>(n) {</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( n <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">0</span> )</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>evens.in <span class="ot">=</span> <span class="cf">function</span>(v) {</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(v[<span class="fu">is.even</span>(v)])</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>The sequence of consecutive differences of a given sequence of numbers, <span class="math inline">\(\{x_1, x_2, x_3, x_4,...\}\)</span>, is the sequence <span class="math inline">\(\{(x_2 - x_1), (x_3 - x_2), (x_4 - x_3),...\}\)</span>. Write a function <code>consecutive.differences(v)</code> that computes the consecutive differences of the elements of some vector <span class="math inline">\(v\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exercise 4 </span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>consecutive.differences <span class="ot">=</span> <span class="cf">function</span>(v) {</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">=</span> v[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">=</span> v[<span class="sc">-</span><span class="fu">length</span>(v)]</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(a<span class="sc">-</span>b)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Write a function <code>histogram.for.simulated.uniform.data(n,num.bars)</code> that will simulate <span class="math inline">\(n\)</span> values following a uniform distribution and then plot the corresponding histogram. The histogram should have <code>num.bars</code> bars (although depending on the random data produced, it is possible that some interior bars might be zero-high).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exercise 5</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>histogram.for.simulated.uniform.data <span class="ot">=</span> <span class="cf">function</span>(n,num.bars) {</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">=</span> <span class="fu">runif</span>(n)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  bin.width <span class="ot">=</span> (<span class="fu">max</span>(data)<span class="sc">-</span><span class="fu">min</span>(data))<span class="sc">/</span>num.bars</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  cols <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"red"</span>,<span class="st">"white"</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  brks <span class="ot">=</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fu">min</span>(data),<span class="at">to=</span><span class="fu">max</span>(data),<span class="at">by=</span>bin.width)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hist</span>(data,<span class="at">breaks=</span>brks,<span class="at">col=</span>cols)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>